# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79821e8debcc31a13c42d9ea3e3109ac1bebcc0575c9992dfec3068fca54ccc175a18d7f490835c78e042826a06b5ebe36e456008677aebaf4a16c26c094d17d

test:
  secret_key_base: ba0219569a37efcba6559ed978511e6419dd8b3bac9f311f69944332a2b1c56b006deee021756d7a98d98f3887e233f991b7f775e2b497917c0545e382d4a693

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
